# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41874d13d68b4491fb6ce8fca32b24b8f7b22d98d92661755441ddb9db0463c630eabc5b5d6c9c1173fbc8fce5f03f314e642e7909e4b0eff0d63710c9641f08

test:
  secret_key_base: 992d5cf3919cf497f7bed55466fa91e4731aeda83fb2210aa3bd9f49f31c10e9d4ce87e35ded75bf80612e3cb538ee21cbc93321d4a8880895eca74e6e1d951e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
